begin;

create schema if not exists private;

create table if not exists public.school_groups (
  id bigint generated by default as identity primary key,
  grade smallint not null,
  section text not null,
  group_name text generated always as (grade::text || section) stored,
  created_at timestamptz not null default now(),
  constraint school_groups_valid_code_check check (
    (grade = 1 and section in ('A', 'B', 'C', 'D'))
    or (grade in (2, 3) and section in ('A', 'B', 'C'))
  ),
  constraint school_groups_grade_section_key unique (grade, section),
  constraint school_groups_group_name_key unique (group_name)
);

create table if not exists public.subjects (
  id bigint generated by default as identity primary key,
  name text not null unique check (length(btrim(name)) between 1 and 120),
  created_at timestamptz not null default now()
);

create table if not exists public.profiles (
  id uuid primary key references auth.users (id) on delete cascade,
  username text not null check (length(btrim(username)) between 3 and 40),
  role text not null default 'student' check (role in ('student', 'admin')),
  group_id bigint references public.school_groups (id) on delete set null,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  constraint profiles_role_group_check check (role <> 'admin' or group_id is null)
);

create unique index if not exists profiles_username_lower_key
  on public.profiles (lower(username));

create index if not exists profiles_group_id_idx on public.profiles (group_id);

create table if not exists public.schedule (
  id bigint generated by default as identity primary key,
  group_id bigint not null references public.school_groups (id) on delete cascade,
  day text not null check (day in ('lunes', 'martes', 'miércoles', 'jueves', 'viernes')),
  subject_id bigint not null references public.subjects (id) on delete restrict,
  constraint schedule_group_day_subject_key unique (group_id, day, subject_id)
);

create index if not exists schedule_group_day_idx on public.schedule (group_id, day);
create index if not exists schedule_subject_id_idx on public.schedule (subject_id);

create table if not exists public.activation_codes (
  id bigint generated by default as identity primary key,
  code_hash text not null unique check (code_hash ~ '^[0-9a-f]{64}$'),
  group_id bigint not null references public.school_groups (id) on delete cascade,
  user_id uuid references public.profiles (id) on delete set null,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  used_at timestamptz,
  revoked_at timestamptz,
  constraint activation_codes_not_used_and_revoked_check check (used_at is null or revoked_at is null)
);

create index if not exists activation_codes_group_id_idx on public.activation_codes (group_id);
create index if not exists activation_codes_user_id_idx on public.activation_codes (user_id);
create index if not exists activation_codes_available_idx
  on public.activation_codes (created_at desc)
  where active and used_at is null and revoked_at is null;

create or replace function private.is_active_user()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.profiles as profile
    where profile.id = (select auth.uid())
      and profile.active
  );
$$;

create or replace function private.is_admin()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.profiles as profile
    where profile.id = (select auth.uid())
      and profile.active
      and profile.role = 'admin'
  );
$$;

create or replace function private.can_read_group(target_group_id bigint)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select private.is_admin()
    or exists (
      select 1
      from public.profiles as profile
      where profile.id = (select auth.uid())
        and profile.active
        and profile.role = 'student'
        and profile.group_id = target_group_id
    );
$$;

revoke all on schema private from public, anon, authenticated;
grant usage on schema private to authenticated, service_role;
revoke all on function private.is_active_user() from public, anon;
revoke all on function private.is_admin() from public, anon;
revoke all on function private.can_read_group(bigint) from public, anon;
grant execute on function private.is_active_user() to authenticated, service_role;
grant execute on function private.is_admin() to authenticated, service_role;
grant execute on function private.can_read_group(bigint) to authenticated, service_role;

alter table public.school_groups enable row level security;
alter table public.school_groups force row level security;
alter table public.subjects enable row level security;
alter table public.subjects force row level security;
alter table public.profiles enable row level security;
alter table public.profiles force row level security;
alter table public.schedule enable row level security;
alter table public.schedule force row level security;
alter table public.activation_codes enable row level security;
alter table public.activation_codes force row level security;

revoke all on public.school_groups, public.subjects, public.profiles, public.schedule, public.activation_codes
  from public, anon, authenticated;
revoke all on all sequences in schema public from public, anon;
revoke all on all sequences in schema public from authenticated;

grant select on public.school_groups, public.subjects to authenticated;
grant select (id, username, role, group_id, active, created_at) on public.profiles to authenticated;
grant update (active) on public.profiles to authenticated;
grant select on public.schedule to authenticated;
grant insert (group_id, day, subject_id), delete on public.schedule to authenticated;
grant insert (name), update (name) on public.subjects to authenticated;
grant select (id, group_id, user_id, active, created_at, used_at, revoked_at)
  on public.activation_codes to authenticated;
grant usage on sequence public.subjects_id_seq, public.schedule_id_seq to authenticated;

 drop policy if exists school_groups_read_active on public.school_groups;
create policy school_groups_read_active on public.school_groups
  for select to authenticated
  using ((select private.is_active_user()));

drop policy if exists subjects_read_active on public.subjects;
create policy subjects_read_active on public.subjects
  for select to authenticated
  using ((select private.is_active_user()));

drop policy if exists subjects_admin_insert on public.subjects;
create policy subjects_admin_insert on public.subjects
  for insert to authenticated
  with check ((select private.is_admin()));

drop policy if exists subjects_admin_update on public.subjects;
create policy subjects_admin_update on public.subjects
  for update to authenticated
  using ((select private.is_admin()))
  with check ((select private.is_admin()));

drop policy if exists profiles_read_self_or_admin on public.profiles;
create policy profiles_read_self_or_admin on public.profiles
  for select to authenticated
  using (id = (select auth.uid()) or (select private.is_admin()));

drop policy if exists profiles_admin_update_status on public.profiles;
create policy profiles_admin_update_status on public.profiles
  for update to authenticated
  using ((select private.is_admin()))
  with check ((select private.is_admin()));

drop policy if exists schedule_read_own_group_or_admin on public.schedule;
create policy schedule_read_own_group_or_admin on public.schedule
  for select to authenticated
  using ((select private.can_read_group(group_id)));

drop policy if exists schedule_admin_insert on public.schedule;
create policy schedule_admin_insert on public.schedule
  for insert to authenticated
  with check ((select private.is_admin()));

drop policy if exists schedule_admin_delete on public.schedule;
create policy schedule_admin_delete on public.schedule
  for delete to authenticated
  using ((select private.is_admin()));

drop policy if exists activation_codes_admin_read on public.activation_codes;
create policy activation_codes_admin_read on public.activation_codes
  for select to authenticated
  using ((select private.is_admin()));

create or replace function public.create_activation_code(p_code_hash text, p_group_id bigint)
returns table (access_code_id bigint, created_at timestamptz)
language plpgsql
security definer
set search_path = ''
as $$
begin
  if not private.is_admin() then
    raise exception using errcode = '42501', message = 'administrator_required';
  end if;

  if p_code_hash is null or p_code_hash !~ '^[0-9a-f]{64}$' then
    raise exception using errcode = '22023', message = 'invalid_code_hash';
  end if;

  return query
    insert into public.activation_codes as inserted_code (code_hash, group_id)
    values (p_code_hash, p_group_id)
    returning inserted_code.id, inserted_code.created_at;
end;
$$;

create or replace function public.revoke_activation_code(p_access_code_id bigint)
returns void
language plpgsql
security definer
set search_path = ''
as $$
begin
  if not private.is_admin() then
    raise exception using errcode = '42501', message = 'administrator_required';
  end if;

  update public.activation_codes
  set active = false, revoked_at = now()
  where id = p_access_code_id
    and active
    and used_at is null
    and revoked_at is null;

  if not found then
    raise exception using errcode = 'P0002', message = 'available_code_not_found';
  end if;
end;
$$;

create or replace function public.activate_student(
  p_code_hash text,
  p_user_id uuid,
  p_username text
)
returns table (group_id bigint, group_name text)
language plpgsql
security definer
set search_path = ''
as $$
declare
  claimed_group_id bigint;
begin
  if p_code_hash is null or p_code_hash !~ '^[0-9a-f]{64}$'
     or p_user_id is null
     or p_username is null
     or length(btrim(p_username)) not between 3 and 40
     or btrim(p_username) !~ '^[a-zA-Z0-9._-]+$' then
    raise exception using errcode = '22023', message = 'invalid_activation_request';
  end if;

  if not exists (select 1 from auth.users as auth_user where auth_user.id = p_user_id) then
    raise exception using errcode = '23503', message = 'auth_user_not_found';
  end if;

  if exists (select 1 from public.profiles as profile where profile.id = p_user_id) then
    raise exception using errcode = '23505', message = 'profile_already_exists';
  end if;

  select code.group_id
    into claimed_group_id
    from public.activation_codes as code
    where code.code_hash = p_code_hash
      and code.active
      and code.used_at is null
      and code.revoked_at is null
    for update;

  if claimed_group_id is null then
    raise exception using errcode = 'P0002', message = 'activation_code_unavailable';
  end if;

  insert into public.profiles (id, username, role, group_id, active)
  values (p_user_id, btrim(p_username), 'student', claimed_group_id, true)
  on conflict do nothing;

  if not found then
    raise exception using errcode = '23505', message = 'profile_or_username_already_exists';
  end if;

  update public.activation_codes
    set user_id = p_user_id,
        active = false,
        used_at = now()
    where code_hash = p_code_hash;

  return query
    select claimed_group_id, school_group.group_name
    from public.school_groups as school_group
    where school_group.id = claimed_group_id;
end;
$$;

revoke all on function public.create_activation_code(text, bigint) from public, anon;
revoke all on function public.revoke_activation_code(bigint) from public, anon;
revoke all on function public.activate_student(text, uuid, text) from public, anon, authenticated;
grant execute on function public.create_activation_code(text, bigint) to authenticated;
grant execute on function public.revoke_activation_code(bigint) to authenticated;
grant execute on function public.activate_student(text, uuid, text) to service_role;

commit;
