project_id = "mochila-supabase-migration"

[api]
enabled = true
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
major_version = 15

[db.seed]
enabled = true
sql_paths = ["./seed.sql"]

[functions.activate]
verify_jwt = false

[functions.login-username]
verify_jwt = false

[functions.admin-access-codes]
verify_jwt = true
